#! /bin/sh

bspc config border_width        2
bspc config window_gap          9

bspc config top_padding 15
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config active_border_color "#3F4B9C"
bspc config focused_border_color "#3F4B9C"
bspc config presel_border_color "#181818"
bspc config urgent_border_color "#C90515"
bspc config focused_locked_border_color "#8c644c"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc desktop 1 -l monocle 
bspc desktop 4 -l monocle
bspc config -d 5 window_gap 0 

bspc rule -a Firefox desktop=^1 focus=on
bspc rule -a mpv desktop=^3 floating=on
bspc rule -a Steam desktop=^6 floating=on
panel&
