#! /bin/sh

source $(dirname $0)/config.sh

while [ $(pgrep -cx panel) -gt 1 ] ; do
	pkill -ox -9 panel
done

killall -9 stalonetray
killall -9 xtitle

# Setup taken from example, tell bspwm to avoid our status/tray and to start
# sending status updates to a FIFO
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe all > "$PANEL_FIFO" &

xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%I:%M %p' > "$PANEL_FIFO" &

. $(dirname $0)/panel_colors.sh

cat "$PANEL_FIFO" | panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -f "$PANEL_FONT_2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

TRAY_GEOM='1x1+180'
sleep 3 && stalonetray --geometry $TRAY_GEOM -i $PANEL_HEIGHT -bg "#34322e" --grow-gravity NE --kludges force_icons_size &
wait

#vim: set ft=sh ts=4 sw=4 tw=500 et :
