#!/bin/bash

bspc config border_width        2
bspc config window_gap         3

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

if [[ `bspc query -M | wc -l` == 2 ]]
then
    bspc monitor HDMI1 -d I II III IV V VI VII VIII IX
    bspc monitor VGA1 -d X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Spotify desktop=^2
bspc rule -a Thunderbird desktop=^6
bspc rule -a Chromium desktop=^9
bspc rule -a Google-chrome-stable desktop=^9
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-pycharm desktop=^4
bspc rule -a jetbrains-idea desktop=^4
bspc rule -a Eclipse desktop=^4
bspc rule -a Skype desktop=^3
bspc rule -a Zathura state=tiled

# mouse support
bspc config pointer_modifier mod4
bspc config click_to_focus true
# manage windows left from previous session
bspc control --adopt-orphans
bspc config wm_name LG3D
wmname LG3D #Sometimes it doesnt work
# do this here so that we know the NetWM anchor window is up
~/dotfiles/bin/java_nonreparenting_wm_hack.sh

panel&
