#!/bin/bash

bspc config border_width        2
bspc config window_gap          3

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer   true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

if [[ `bspc query -M | wc -l` == 2 ]]
then
    bspc wm -O DP3 eDP1
    bspc monitor '^1' -d I II III IV V VI VII VIII IX
    bspc monitor '^2' -d X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# xprop | grep WM_CLASS
bspc rule -a Spotify desktop=^2
bspc rule -a vlc desktop=^2
bspc rule -a jetbrains-pycharm desktop=^4
bspc rule -a jetbrains-pycharm-ce desktop=^4
bspc rule -a jetbrains-idea desktop=^4
bspc rule -a jetbrains-idea-ce desktop=^4
bspc rule -a Eclipse desktop=^4
bspc rule -a Gimp desktop=^6
bspc rule -a Thunderbird desktop=^7
bspc rule -a TelegramDesktop desktop=^7
bspc rule -a firefox desktop=^8
bspc rule -a Chromium desktop=^9
bspc rule -a Google-chrome desktop=^9
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off
bspc rule -a zoom state=floating
bspc rule -a Nextcloud state=floating

# mouse support
bspc config pointer_modifier mod4
bspc config click_to_focus button1
# manage windows left from previous session
bspc wm --adopt-orphans

# Fix Java app issues
export _JAVA_AWT_WM_NONREPARENTING=1
export AWT_TOOLKIT=MToolkit
bspc config wm_name LG3D
wmname LG3D #Sometimes it doesnt work
# do this here so that we know the NetWM anchor window is up
~/dotfiles/bin/java_nonreparenting_wm_hack.sh

~/dotfiles/polybar/launch.sh
